<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Favorite</name>
   <tag></tag>
   <elementGuidId>45e1056a-2a02-4a59-b852-eb75f8de7fed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/nav/span[2]/span/a/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.favorite-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>40d06018-61e7-477c-9792-c36ec9ef423f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>favorite-button</value>
      <webElementGuid>6cfc214f-b4f9-4f2c-bc41-4a8896b67738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Favorite</value>
      <webElementGuid>3b677991-1758-4f03-a85f-3a2782869fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/nav[1]/span[2]/span[1]/a[1]/a[@class=&quot;favorite-button&quot;]</value>
      <webElementGuid>18d81089-a72c-4a0c-b0d5-d804d6a6c86c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/nav/span[2]/span/a/a</value>
      <webElementGuid>177c87fc-5819-4ab9-9a0e-d5385ee81215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Favorite')]</value>
      <webElementGuid>f7486004-05a1-487c-853f-4909a36a98f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Discovery'])[1]/following::a[2]</value>
      <webElementGuid>a64486ab-7486-42cc-806b-ecd18bf15303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Anime Lookup'])[1]/following::a[3]</value>
      <webElementGuid>e89755b2-2d12-4096-ba47-04f99c5606a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/preceding::a[1]</value>
      <webElementGuid>d337bc78-c7cd-4032-aa13-752319a1e0ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hello, TokiDokor'])[1]/preceding::a[2]</value>
      <webElementGuid>6ecb3e50-21ea-49bf-901e-8e751e70988a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Favorite']/parent::*</value>
      <webElementGuid>c09bbec4-9e88-4d7d-9c4d-ced06960e1e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/span/a/a</value>
      <webElementGuid>e7da7b67-b0d9-4803-927e-ff80bbef1073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Favorite' or . = 'Favorite')]</value>
      <webElementGuid>d4a38d1f-8ee9-41ee-9f59-9b3c8c8eaf9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ranking: #305'])[1]/preceding::a[2]</value>
      <webElementGuid>6bd5e5a5-33e9-4a97-86c6-74db5ffd25cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
