<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add to list</name>
   <tag></tag>
   <elementGuidId>3e54996d-9685-41c3-8c14-06a37ec8a38a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/span/h3/span/span/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.submit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>72c2ea23-7101-4895-9e2d-d810314e9350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f7506f2a-de97-4a7e-aa5f-68a537abd979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add to list </value>
      <webElementGuid>7c0ba949-d0cd-483d-9ce3-52d9a0c84212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;anime-title&quot;]/div[@class=&quot;content-block&quot;]/span[1]/h3[1]/span[1]/span[1]/button[@class=&quot;submit&quot;]</value>
      <webElementGuid>3a4e71ce-51dc-4491-876e-0db5c916907e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/span/h3/span/span/button</value>
      <webElementGuid>c355efd9-ac30-44b9-a736-f9c6645a7d50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Synopsis'])[1]/preceding::button[1]</value>
      <webElementGuid>9fc20271-43bf-4d18-b32e-127c0eb22ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Watch trailer'])[1]/preceding::button[1]</value>
      <webElementGuid>36e17679-8861-4d3d-a97b-f6bfa975ee5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add to list']/parent::*</value>
      <webElementGuid>d6dd3476-d07a-4083-b90d-92944eff8dbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>af0b3b92-15c4-4adf-944c-9a540f827402</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = ' Add to list ' or . = ' Add to list ')]</value>
      <webElementGuid>444aa37f-0285-491d-b818-772d26c381a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
