<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Watch trailer</name>
   <tag></tag>
   <elementGuidId>24e8afcf-a396-419d-8937-ac5f480c4fa1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.anime-video</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>31330d8a-e7e8-4318-bad1-fa617c2e5b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>anime-video</value>
      <webElementGuid>19c2246e-2eff-41ff-8184-396939e3793c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Watch trailer</value>
      <webElementGuid>6379420d-7572-412a-8829-d0bdf9f8936e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;anime-description&quot;]/div[@class=&quot;anime-video&quot;]</value>
      <webElementGuid>7950bc3d-42d7-4c52-abdd-49f01769cece</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div[2]</value>
      <webElementGuid>86359a8e-620f-489e-93e1-dabdfdf8de5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Synopsis'])[1]/following::div[1]</value>
      <webElementGuid>ace483ec-f7cb-47a2-9507-bd2cde48fc5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to list'])[1]/following::div[3]</value>
      <webElementGuid>b69daeeb-b129-4521-b3b3-420edb667fc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>58d6eee0-8d43-4758-aa71-a190fa918f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Watch trailer' or . = 'Watch trailer')]</value>
      <webElementGuid>9f6dab83-86b1-43fd-bbf4-03d09efa8097</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
