<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Yuru CampYuru Camp Season 2Yuru YuriYur_78daa5</name>
   <tag></tag>
   <elementGuidId>15c8501d-8d96-4fee-8bf6-2af031f83460</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.anime-cards</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7a76fda2-6bcb-48aa-b39b-a3d08a24f199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>anime-cards</value>
      <webElementGuid>8a947568-054b-4ee3-9573-97389e043d01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Yuru Camp△☆Yuru Camp△ Season 2☆Yuru Yuri♪♪☆Yuru Yuri☆Yuru Yuri San☆Hai!☆Yuru Yuri Nachuyachumi!☆Yuru Yuri Nachuyachumi!+☆Yuru Camp△ Specials☆Yuru Yuri,☆Yuru Camp△ Movie☆</value>
      <webElementGuid>45af1c1c-00c3-47b9-84bf-365bce485465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;centered&quot;]/div[@class=&quot;anime-cards&quot;]</value>
      <webElementGuid>ca68754d-ae3c-409b-b822-44c1643b8d9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div</value>
      <webElementGuid>ce809b0a-6885-4573-abf5-0f20f30a54cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::div[2]</value>
      <webElementGuid>61d83080-f649-48c4-9dde-830618634454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/following::div[2]</value>
      <webElementGuid>05ee93f6-1bd1-4937-a076-a8b2b0280b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div</value>
      <webElementGuid>3cdea2ac-f583-4dbe-bc68-6aa11e3ec3fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Yuru Camp△☆Yuru Camp△ Season 2☆Yuru Yuri♪♪☆Yuru Yuri☆Yuru Yuri San☆Hai!☆Yuru Yuri Nachuyachumi!☆Yuru Yuri Nachuyachumi!+☆Yuru Camp△ Specials☆Yuru Yuri,☆Yuru Camp△ Movie☆' or . = 'Yuru Camp△☆Yuru Camp△ Season 2☆Yuru Yuri♪♪☆Yuru Yuri☆Yuru Yuri San☆Hai!☆Yuru Yuri Nachuyachumi!☆Yuru Yuri Nachuyachumi!+☆Yuru Camp△ Specials☆Yuru Yuri,☆Yuru Camp△ Movie☆')]</value>
      <webElementGuid>f423df63-2dac-466d-9351-963e384b471b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
