<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Description_search-box</name>
   <tag></tag>
   <elementGuidId>b6e2f2d6-a28d-4ccc-bc5b-91bedb803611</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form.search-box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>60c55216-342d-4cad-bcad-a0dbade497a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>search-box</value>
      <webElementGuid>63d526d6-6e7e-42a1-8f63-6dd2b81a97bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;home&quot;]/form[@class=&quot;search-box&quot;]</value>
      <webElementGuid>a5d44693-7669-4ad5-bf38-98c5ad4a5ab5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/form</value>
      <webElementGuid>493d6b10-7da9-40c6-ab74-75a02570f574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::form[1]</value>
      <webElementGuid>18c57b1d-3a02-4d81-82f3-28f6b9f12b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/following::form[1]</value>
      <webElementGuid>ddd56013-5397-471b-875d-935ac390c26a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>c11892d6-ecbb-4475-96fd-51c7f5929274</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
