<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Ranking 305Score 8.23Popularity 596</name>
   <tag></tag>
   <elementGuidId>28617840-af77-4280-a48c-8acda3cea9f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>fd6ab66f-1593-4edb-a0fc-229c75cf1b90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header</value>
      <webElementGuid>72d2fd01-46fb-4b9b-aadb-d6b7f93d0d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ranking: #305Score: 8.23Popularity: #596</value>
      <webElementGuid>84064d6d-8ba1-4d8f-af2d-3b14d468b6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;anime-title&quot;]/div[@class=&quot;content-block&quot;]/h2[@class=&quot;header&quot;]</value>
      <webElementGuid>785e3d38-f499-42ed-8cd0-29d9a8736a1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/h2</value>
      <webElementGuid>c9ea7627-3c9a-474d-bdd9-7ae58c0a9f72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/following::h2[1]</value>
      <webElementGuid>15625f24-9bfc-415f-84cf-23c0d34d44b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Favorite'])[1]/following::h2[1]</value>
      <webElementGuid>b2306b3a-654c-43d5-81a5-e294f10cb45b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>a3224ab4-60ab-4086-9538-772c05d32842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Ranking: #305Score: 8.23Popularity: #596' or . = 'Ranking: #305Score: 8.23Popularity: #596')]</value>
      <webElementGuid>0d00bf26-07e1-4d6e-8de0-78473544d739</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
