<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Synopsis</name>
   <tag></tag>
   <elementGuidId>a8610da4-6a04-4626-b017-a0a8a69ee09e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div[2]/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.anime-synopsis > h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>bd30bb7e-58c5-425a-88c5-f2206ece6090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Synopsis</value>
      <webElementGuid>83ba4260-571b-4734-9c2a-a10318ed7cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;anime-description&quot;]/div[@class=&quot;anime-synopsis&quot;]/h2[1]</value>
      <webElementGuid>b5c20aac-1af6-4018-a962-89c2709fa2e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/h2</value>
      <webElementGuid>2c93b614-2d72-43d6-b5ad-c97dae701b73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to list'])[1]/following::h2[1]</value>
      <webElementGuid>810fd5cb-7db8-4bbc-8bfc-6708ca3e3a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Watch trailer'])[1]/preceding::h2[1]</value>
      <webElementGuid>aa7578b9-eb28-41fb-a314-9ce790e50a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Synopsis']/parent::*</value>
      <webElementGuid>46174f07-38f6-4c09-bbd5-b44709d5919b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h2</value>
      <webElementGuid>9d96aa93-c29b-4147-8da7-88a8cf9ff90d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Synopsis' or . = 'Synopsis')]</value>
      <webElementGuid>e64c0e65-69a5-4c6d-9eaa-a8f387148db3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
