<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Studio A-1 Pictures</name>
   <tag></tag>
   <elementGuidId>a4e17c30-c342-49d4-96db-ae757fbdc10e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/h4[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>c83c99ec-e48f-42d7-b4d9-b899d4e68364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Studio: A-1 Pictures</value>
      <webElementGuid>fceff01d-2b97-4943-8548-4ac8e0f591bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;anime-title&quot;]/div[@class=&quot;content-block&quot;]/h4[4]</value>
      <webElementGuid>ab67eb01-3471-48ba-9641-84fe629dd3b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/h4[4]</value>
      <webElementGuid>f80af0b7-ef03-4227-9d71-501b9c74cbc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Finished Airing'])[1]/following::h4[1]</value>
      <webElementGuid>acf301bb-f9c5-4d7d-add4-1266e71daa18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Studio: A-1 Pictures']/parent::*</value>
      <webElementGuid>dc136d01-c008-4b3d-ab2b-bb8f6f9b6109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4[4]</value>
      <webElementGuid>0af06221-b7f9-4995-a44b-b3527e949c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'Studio: A-1 Pictures' or . = 'Studio: A-1 Pictures')]</value>
      <webElementGuid>fabb3a17-679e-4f8f-9810-809cdfbc71ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
