<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nav_Anime LookupDiscoveryLog in</name>
   <tag></tag>
   <elementGuidId>7f59cac1-174a-41fa-b22a-724cc833d196</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nav</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/nav</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nav</value>
      <webElementGuid>8f5129cc-07cf-4573-bf7f-2c399efb0788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Anime LookupDiscoveryLog in</value>
      <webElementGuid>d2472167-24ba-47f3-9bf1-6624f0d37402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/nav[1]</value>
      <webElementGuid>f6a2c7c7-178e-4bb8-a327-a05046dc9a15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/nav</value>
      <webElementGuid>53884b0e-c2e1-4ffa-8612-c168d73b6001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav</value>
      <webElementGuid>5e72dc16-e0c4-4f44-9594-f32e0116e724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nav[(text() = 'Anime LookupDiscoveryLog in' or . = 'Anime LookupDiscoveryLog in')]</value>
      <webElementGuid>2f189df4-527a-4414-8361-b031208b3c92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
