<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Navigator_Div</name>
   <tag></tag>
   <elementGuidId>860ac66a-c09c-469b-b082-d3fc97471175</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>nav</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/nav</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nav</value>
      <webElementGuid>599af66e-8917-4cc8-b38b-0fe6a94cd816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Anime LookupDiscoveryLog in</value>
      <webElementGuid>7efbe569-6afb-49f4-b93e-575bd68688a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/nav[1]</value>
      <webElementGuid>0be70f0c-26d5-4afa-9d6a-2648704db8d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/nav</value>
      <webElementGuid>a982867a-0d81-4eec-b855-255a55dd4546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav</value>
      <webElementGuid>89b017d7-a6eb-4dab-b02e-ddaf106696b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nav[(text() = 'Anime LookupDiscoveryLog in' or . = 'Anime LookupDiscoveryLog in')]</value>
      <webElementGuid>1923017f-dafd-4394-90a9-6e3b344c02d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
